# Gradle JVM 参数
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Java 17
org.gradle.java.home=/usr/lib/jvm/java-17-openjdk-amd64

# 启用 AndroidX
android.useAndroidX=true

# Kotlin 代码风格（official = 官方推荐风格）
kotlin.code.style=official

# 非传递 R class（每个模块只生成自己的 R 类，提升构建速度）
android.nonTransitiveRClass=true

# 代理设置
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=18080
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=18080
